### ISSUE TITLE
souci pour installation en mode developpement

### ISSUE THREAD

**Issue by kerphi** [BibCnrs/BibCnrs#52]
J'ai suivi les instructions du README
docker-compose build
make composer install
make run-dev
DB_PASSWORD=test make load-fixtures

et je suis tombé sur cette erreur au moment de faire le make composer install :
![image](https://cloud.githubusercontent.com/assets/328244/17408807/efcbc570-5a6c-11e6-81b2-4d45250d3231.png)

puis je suis tombé sur cette erreur au chargement de la page http://localhost:8080/  (probablement en relation avec l'erreur précédente ?)
Fatal error: Class 'Timber' not found in /var/www/html/wp-content/themes/portail/home.php on line 4

**Comment by ThieryMichel** [comment]
Il faut faire make install et non make composer install.
Il faut également activer timber ainsi que dans tout les plugin dans l'admin de wordpress.

**Comment by kerphi** [comment]
Ok, j'ai nettoyé mes vieux conteneurs docker et j'ai refais depuis zero comme tu l'as indiqué.
Ca fonctionne mieux.
